### ISSUE TITLE
Hey there 

### ISSUE THREAD

**Issue by scotcha1** [zendesklabs/bulk_delete_orgs_app#7]
We have over 45,000 organizations (long story).

We get an error telling us that the app is broken if we try to delete that many. Any suggestions?

**Comment by niall3rs** [comment]
Hi, thanks for reaching out! Yeah, I just got a similar report recently with ~52k orgs. It seems like the deletion job is timing out for very large numbers, which I hadn't fully tested for.

I'm going to work on this soon - the best I can recommend for now is to work in smaller batches. It seems like 750 at a time goes through without issues but it's starting to error at around the 1000 mark.

Sorry for the inconvenience - I'll let you know when it's scaled up to handle larger jobs.

**Comment by scotcha1** [comment]
Thanks!

Quick question for you, how do I do 750 at a time? If I select all on a
page and go to next page, is the previous page selections saved?

That's helpful if so.

**Comment by niall3rs** [comment]
Yep - selections are stored as you toggle the pages, so you can do batches of pages at a time.

I've actually just added functionality to handle larger requests now, and am testing it with ~50k orgs. It's looking good! Taking a bit of time to get through it all, but no errors so far.

If it all goes well, I'll submit the updated version to the Marketplace, but I can also provide you with the .zip to [install it as a private app](https://support.zendesk.com/hc/en-us/articles/203691246) for you to run locally if you'd like.

**Comment by scotcha1** [comment]
Awesome!

I'll try the multi page selector today!

As for running it locally, I'm admittedly not too technical, but happy to
learn/give it a try. Is it complex?

**Comment by niall3rs** [comment]
Not at all! The app itself is all contained in this zip file - [click here to download](https://github.com/zendesklabs/bulk_delete_orgs_app/files/464311/bdo.zip).

In order to install that version in your instance of Zendesk, you can follow the steps at https://support.zendesk.com/hc/en-us/articles/203691246.

I'd have to remind you to use this at your own risk. It's not been rigorously tested (all done by myself this afternoon, as it happens) but I've found it to work just fine. As a heads up it took about half an hour to run the entire deletion for all ~50,000 orgs in my testing.

Hope it helps! I'm always keen to hear any feedback you may have.
